#!/usr/bin/env ruby
# frozen_string_literal: true

require './calculate'
require './display'

print "\t\t#{$sizes.join "\t"}\n"

$widths.each do |width|
  %i[ball instep heel].each do |measure|
    print "#{width}\t#{measure}\t"
    print $sizes.map { |size| display $data[size][width][measure] }.join "\t"
    print "\n"
  end
end
